### ISSUE TITLE
Gameplay Display and Model Render

### ISSUE THREAD

**Issue by Millennium-stack** [Millennium-stack/OpenGLGame3D#1]
# Description #

The initial development of the game involves developing the gameplay display for the game as well as developing the codebase for rendering models in our game world.

## Sub-Feature ##
- Developing the gameplay display for the game.
- Rendering models to the game.

## Dependencies ##
None

## Milestones ##
- [ ] Creating the codebase for the gameplay display.
- [ ] Creating the codebase for rendering models in the game.
- [ ] Creating tests for the developed codebase.

## Members/Member ##
- Name (Github Handle) (xyz@email.com)
- Millennium Singha (@Millennium-stack) (myhacks909@gmail.com)
