### ISSUE TITLE
Gameplay Display Design

### ISSUE THREAD

**Issue by Millennium-stack** [Millennium-stack/OpenGLGame3D#1]
# Description

This feature involves working on the initial gameplay display design. It aims to develop models to be used for future rendering purposes for the 3D game.

## Sub-Feature
- Gameplay display.
- Rendering models to the display.
- Polishing render models for the 3D game for efficient model rendering.

## Dependencies
- The LWJGL libraries need to be added to the project path.

### Milestones ###
List of sub-feature to be done in sprint 1 of the project development
- [ ] Design the initial gameplay display for the game.
- [ ] Render models to the gameplay display.
- [ ] Polish the codes designed for rendering for efficiency.

## Example ##
A gameplay display of 1280x720 size with a model rendered within the display.
![image](https://user-images.githubusercontent.com/59429290/98446745-ac2ca880-2145-11eb-91b4-6d4817689111.png)

# Members #
- Name (Github Handle) (xyz@email.com)
- Millennium Singha (@Millennium-stack) (myhacks909@gmail.com)
